name: test
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:   ['ubuntu', 'macos', 'windows']
        ruby: ['3.3']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install automake (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install automake libdeflate
          bundle exec rake htslib:build
      - name: Install libdeflate & libcurl4 (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt update -y
          sudo apt install -yq libdeflate-dev libcurl4-openssl-dev
          bundle exec rake htslib:build
      - name: Update package databases (windows)
        if: ${{ matrix.os == 'windows' }}
        run: |
          ridk exec pacman -Syu --noconfirm
      - name: Build and test with Rake
        run: |
          bundle exec rake
