name: test
on: [push, pull_request]
jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os:   ['ubuntu', 'macos']
        ruby: ['2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install automake (macos)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install automake
      - run: |
          bundle exec rake htslib:build
          ldd vendor/libhts*
      - name: Build and test with Rake
        run: |
          bundle exec rake htslib:build
          bundle exec rake
